name: Newman extra-html-report deploy to github page 

on: [workflow_dispatch,push]
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create dir
        run: |
          mkdir -p testResults

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - run: npm i npm@latest
      - run: npm i
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      
      - name: Run POSTMAN collection
        run: |
          newman run "petStore.postman_collection.json" -e "petStore.postman_environment.json" -r cli,htmlextra --reporter-htmlextra-export testResults/index.html || true
                
      - name: Output the results
        uses: actions/upload-artifact@v4
        with:
          name: Reporter
          path: testResults

      - name: Publish reports
        uses: PavanMudigonda/html-reporter-github-pages@v1.4
        with:
          test_results: test-results
          order: ascending
          gh_pages: gh_pages          
          token: ${{ secrets.CI_TOKEN }}
