name: Newman Allure Report Deploy to GitHub Pages

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '00 18 * * *'

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create result directories
        run: |
          mkdir -p testResults/allure-results

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - run: npm install -g npm@latest
      - run: npm install
      - name: Install Newman and Allure Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-allure

      - name: Run POSTMAN collection with Allure reporter
        run: |
          newman run "petStore.postman_collection.json" \
            -e "petStore.postman_environment.json" \
            -r cli,allure --reporter-allure-export testResults/allure-results || true

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy previous history if exists
        run: |
          mkdir -p testResults/allure-report/history
          if [ -d gh-pages/allure-history ]; then
            cp -R gh-pages/allure-history/* testResults/allure-results/history || true
          fi

      - name: Generate Allure report
        run: |
          allure generate testResults/allure-results --clean -o testResults/allure-report

      - name: Move current history for next build
        run: |
          mkdir -p gh-pages/allure-history
          cp -R testResults/allure-report/history gh-pages/allure-history || true

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ci_token }}
          publish_branch: gh-pages
          publish_dir: testResults/allure-report
          keep_files: true
